// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: sealed/sealed_product.proto

package sealed

import (
	meta "github.com/stevezaluk/mtgjson-models/meta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SealedProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardCount     int64                  `protobuf:"varint,1,opt,name=cardCount,proto3" json:"cardCount,omitempty" bson:"cardCount"`      // @gotags: bson:"cardCount"
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty" bson:"category"`         // @gotags: bson:"category"
	Contents      *SealedProductContents `protobuf:"bytes,3,opt,name=contents,proto3" json:"contents,omitempty" bson:"contents"`         // @gotags: bson:"contents"
	Identifiers   *meta.CardIdentifiers  `protobuf:"bytes,4,opt,name=identifiers,proto3" json:"identifiers,omitempty" bson:"identifiers"`   // @gotags: bson:"identifiers"
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty" bson:"name"`                 // @gotags: bson:"name"
	ProductSize   int64                  `protobuf:"varint,6,opt,name=productSize,proto3" json:"productSize,omitempty" bson:"productSize"`  // @gotags: bson:"productSize"
	PurchaseUrls  *meta.PurchaseUrls     `protobuf:"bytes,7,opt,name=purchaseUrls,proto3" json:"purchaseUrls,omitempty" bson:"purchaseUrls"` // @gotags: bson:"purchaseUrls"
	ReleaseDate   string                 `protobuf:"bytes,8,opt,name=releaseDate,proto3" json:"releaseDate,omitempty" bson:"releaseDate"`   // @gotags: bson:"releaseDate"
	Subtype       string                 `protobuf:"bytes,9,opt,name=subtype,proto3" json:"subtype,omitempty" bson:"subtype"`           // @gotags: bson:"subtype"
	Uuid          string                 `protobuf:"bytes,10,opt,name=uuid,proto3" json:"uuid,omitempty" bson:"uuid"`                // @gotags: bson:"uuid"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealedProduct) Reset() {
	*x = SealedProduct{}
	mi := &file_sealed_sealed_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealedProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealedProduct) ProtoMessage() {}

func (x *SealedProduct) ProtoReflect() protoreflect.Message {
	mi := &file_sealed_sealed_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealedProduct.ProtoReflect.Descriptor instead.
func (*SealedProduct) Descriptor() ([]byte, []int) {
	return file_sealed_sealed_product_proto_rawDescGZIP(), []int{0}
}

func (x *SealedProduct) GetCardCount() int64 {
	if x != nil {
		return x.CardCount
	}
	return 0
}

func (x *SealedProduct) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SealedProduct) GetContents() *SealedProductContents {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *SealedProduct) GetIdentifiers() *meta.CardIdentifiers {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

func (x *SealedProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SealedProduct) GetProductSize() int64 {
	if x != nil {
		return x.ProductSize
	}
	return 0
}

func (x *SealedProduct) GetPurchaseUrls() *meta.PurchaseUrls {
	if x != nil {
		return x.PurchaseUrls
	}
	return nil
}

func (x *SealedProduct) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *SealedProduct) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *SealedProduct) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_sealed_sealed_product_proto protoreflect.FileDescriptor

const file_sealed_sealed_product_proto_rawDesc = "" +
	"\n" +
	"\x1bsealed/sealed_product.proto\x12\x06sealed\x1a$sealed/sealed_product_contents.proto\x1a\x16meta/identifiers.proto\x1a\x18meta/purchase_urls.proto\"\xfb\x02\n" +
	"\rSealedProduct\x12\x1c\n" +
	"\tcardCount\x18\x01 \x01(\x03R\tcardCount\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x129\n" +
	"\bcontents\x18\x03 \x01(\v2\x1d.sealed.SealedProductContentsR\bcontents\x127\n" +
	"\videntifiers\x18\x04 \x01(\v2\x15.meta.CardIdentifiersR\videntifiers\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vproductSize\x18\x06 \x01(\x03R\vproductSize\x126\n" +
	"\fpurchaseUrls\x18\a \x01(\v2\x12.meta.PurchaseUrlsR\fpurchaseUrls\x12 \n" +
	"\vreleaseDate\x18\b \x01(\tR\vreleaseDate\x12\x18\n" +
	"\asubtype\x18\t \x01(\tR\asubtype\x12\x12\n" +
	"\x04uuid\x18\n" +
	" \x01(\tR\x04uuidB-Z+github.com/stevezaluk/mtgjson-models/sealedb\x06proto3"

var (
	file_sealed_sealed_product_proto_rawDescOnce sync.Once
	file_sealed_sealed_product_proto_rawDescData []byte
)

func file_sealed_sealed_product_proto_rawDescGZIP() []byte {
	file_sealed_sealed_product_proto_rawDescOnce.Do(func() {
		file_sealed_sealed_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sealed_sealed_product_proto_rawDesc), len(file_sealed_sealed_product_proto_rawDesc)))
	})
	return file_sealed_sealed_product_proto_rawDescData
}

var file_sealed_sealed_product_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sealed_sealed_product_proto_goTypes = []any{
	(*SealedProduct)(nil),         // 0: sealed.SealedProduct
	(*SealedProductContents)(nil), // 1: sealed.SealedProductContents
	(*meta.CardIdentifiers)(nil),  // 2: meta.CardIdentifiers
	(*meta.PurchaseUrls)(nil),     // 3: meta.PurchaseUrls
}
var file_sealed_sealed_product_proto_depIdxs = []int32{
	1, // 0: sealed.SealedProduct.contents:type_name -> sealed.SealedProductContents
	2, // 1: sealed.SealedProduct.identifiers:type_name -> meta.CardIdentifiers
	3, // 2: sealed.SealedProduct.purchaseUrls:type_name -> meta.PurchaseUrls
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sealed_sealed_product_proto_init() }
func file_sealed_sealed_product_proto_init() {
	if File_sealed_sealed_product_proto != nil {
		return
	}
	file_sealed_sealed_product_contents_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sealed_sealed_product_proto_rawDesc), len(file_sealed_sealed_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sealed_sealed_product_proto_goTypes,
		DependencyIndexes: file_sealed_sealed_product_proto_depIdxs,
		MessageInfos:      file_sealed_sealed_product_proto_msgTypes,
	}.Build()
	File_sealed_sealed_product_proto = out.File
	file_sealed_sealed_product_proto_goTypes = nil
	file_sealed_sealed_product_proto_depIdxs = nil
}
