// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: sealed/sealed_product_contents.proto

package sealed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SealedProductContents struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Card          *SealedProductCard                `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty" bson:"card"`                                                                                   // @gotags: bson:"card"
	Deck          *SealedProductDeck                `protobuf:"bytes,2,opt,name=deck,proto3" json:"deck,omitempty" bson:"deck"`                                                                                   // @gotags: bson:"deck"
	Other         *SealedProductOther               `protobuf:"bytes,3,opt,name=other,proto3" json:"other,omitempty" bson:"other"`                                                                                 // @gotags: bson:"other"
	Pack          *SealedProductPack                `protobuf:"bytes,4,opt,name=pack,proto3" json:"pack,omitempty" bson:"pack"`                                                                                   // @gotags: bson:"pack"
	Sealed        *SealedProductSealed              `protobuf:"bytes,5,opt,name=sealed,proto3" json:"sealed,omitempty" bson:"sealed"`                                                                               // @gotags: bson:"sealed"
	Variable      map[string]*SealedProductContents `protobuf:"bytes,6,rep,name=variable,proto3" json:"variable,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" bson:"variable"` // @gotags: bson:"variable"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealedProductContents) Reset() {
	*x = SealedProductContents{}
	mi := &file_sealed_sealed_product_contents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealedProductContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealedProductContents) ProtoMessage() {}

func (x *SealedProductContents) ProtoReflect() protoreflect.Message {
	mi := &file_sealed_sealed_product_contents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealedProductContents.ProtoReflect.Descriptor instead.
func (*SealedProductContents) Descriptor() ([]byte, []int) {
	return file_sealed_sealed_product_contents_proto_rawDescGZIP(), []int{0}
}

func (x *SealedProductContents) GetCard() *SealedProductCard {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *SealedProductContents) GetDeck() *SealedProductDeck {
	if x != nil {
		return x.Deck
	}
	return nil
}

func (x *SealedProductContents) GetOther() *SealedProductOther {
	if x != nil {
		return x.Other
	}
	return nil
}

func (x *SealedProductContents) GetPack() *SealedProductPack {
	if x != nil {
		return x.Pack
	}
	return nil
}

func (x *SealedProductContents) GetSealed() *SealedProductSealed {
	if x != nil {
		return x.Sealed
	}
	return nil
}

func (x *SealedProductContents) GetVariable() map[string]*SealedProductContents {
	if x != nil {
		return x.Variable
	}
	return nil
}

var File_sealed_sealed_product_contents_proto protoreflect.FileDescriptor

const file_sealed_sealed_product_contents_proto_rawDesc = "" +
	"\n" +
	"$sealed/sealed_product_contents.proto\x12\x06sealed\x1a sealed/sealed_product_card.proto\x1a sealed/sealed_product_deck.proto\x1a!sealed/sealed_product_other.proto\x1a sealed/sealed_product_pack.proto\x1a\"sealed/sealed_product_sealed.proto\"\xb0\x03\n" +
	"\x15SealedProductContents\x12-\n" +
	"\x04card\x18\x01 \x01(\v2\x19.sealed.SealedProductCardR\x04card\x12-\n" +
	"\x04deck\x18\x02 \x01(\v2\x19.sealed.SealedProductDeckR\x04deck\x120\n" +
	"\x05other\x18\x03 \x01(\v2\x1a.sealed.SealedProductOtherR\x05other\x12-\n" +
	"\x04pack\x18\x04 \x01(\v2\x19.sealed.SealedProductPackR\x04pack\x123\n" +
	"\x06sealed\x18\x05 \x01(\v2\x1b.sealed.SealedProductSealedR\x06sealed\x12G\n" +
	"\bvariable\x18\x06 \x03(\v2+.sealed.SealedProductContents.VariableEntryR\bvariable\x1aZ\n" +
	"\rVariableEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.sealed.SealedProductContentsR\x05value:\x028\x01B-Z+github.com/stevezaluk/mtgjson-models/sealedb\x06proto3"

var (
	file_sealed_sealed_product_contents_proto_rawDescOnce sync.Once
	file_sealed_sealed_product_contents_proto_rawDescData []byte
)

func file_sealed_sealed_product_contents_proto_rawDescGZIP() []byte {
	file_sealed_sealed_product_contents_proto_rawDescOnce.Do(func() {
		file_sealed_sealed_product_contents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sealed_sealed_product_contents_proto_rawDesc), len(file_sealed_sealed_product_contents_proto_rawDesc)))
	})
	return file_sealed_sealed_product_contents_proto_rawDescData
}

var file_sealed_sealed_product_contents_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sealed_sealed_product_contents_proto_goTypes = []any{
	(*SealedProductContents)(nil), // 0: sealed.SealedProductContents
	nil,                           // 1: sealed.SealedProductContents.VariableEntry
	(*SealedProductCard)(nil),     // 2: sealed.SealedProductCard
	(*SealedProductDeck)(nil),     // 3: sealed.SealedProductDeck
	(*SealedProductOther)(nil),    // 4: sealed.SealedProductOther
	(*SealedProductPack)(nil),     // 5: sealed.SealedProductPack
	(*SealedProductSealed)(nil),   // 6: sealed.SealedProductSealed
}
var file_sealed_sealed_product_contents_proto_depIdxs = []int32{
	2, // 0: sealed.SealedProductContents.card:type_name -> sealed.SealedProductCard
	3, // 1: sealed.SealedProductContents.deck:type_name -> sealed.SealedProductDeck
	4, // 2: sealed.SealedProductContents.other:type_name -> sealed.SealedProductOther
	5, // 3: sealed.SealedProductContents.pack:type_name -> sealed.SealedProductPack
	6, // 4: sealed.SealedProductContents.sealed:type_name -> sealed.SealedProductSealed
	1, // 5: sealed.SealedProductContents.variable:type_name -> sealed.SealedProductContents.VariableEntry
	0, // 6: sealed.SealedProductContents.VariableEntry.value:type_name -> sealed.SealedProductContents
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sealed_sealed_product_contents_proto_init() }
func file_sealed_sealed_product_contents_proto_init() {
	if File_sealed_sealed_product_contents_proto != nil {
		return
	}
	file_sealed_sealed_product_card_proto_init()
	file_sealed_sealed_product_deck_proto_init()
	file_sealed_sealed_product_other_proto_init()
	file_sealed_sealed_product_pack_proto_init()
	file_sealed_sealed_product_sealed_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sealed_sealed_product_contents_proto_rawDesc), len(file_sealed_sealed_product_contents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sealed_sealed_product_contents_proto_goTypes,
		DependencyIndexes: file_sealed_sealed_product_contents_proto_depIdxs,
		MessageInfos:      file_sealed_sealed_product_contents_proto_msgTypes,
	}.Build()
	File_sealed_sealed_product_contents_proto = out.File
	file_sealed_sealed_product_contents_proto_goTypes = nil
	file_sealed_sealed_product_contents_proto_depIdxs = nil
}
