// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: booster/booster_sheet.proto

package booster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoosterSheet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AllowDuplicates bool                   `protobuf:"varint,1,opt,name=allowDuplicates,proto3" json:"allowDuplicates,omitempty" bson:"allowDuplicates"`                                                       // @gotags: bson:"allowDuplicates"
	BalanceColors   bool                   `protobuf:"varint,2,opt,name=balanceColors,proto3" json:"balanceColors,omitempty" bson:"balanceColors"`                                                           // @gotags: bson:"balanceColors"
	Cards           map[string]int64       `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value" bson:"cards"` // @gotags: bson:"cards"
	Foil            bool                   `protobuf:"varint,4,opt,name=foil,proto3" json:"foil,omitempty" bson:"foil"`                                                                             // @gotags: bson:"foil"
	Fixed           bool                   `protobuf:"varint,5,opt,name=fixed,proto3" json:"fixed,omitempty" bson:"fixed"`                                                                           // @gotags: bson:"fixed"
	TotalWeight     int64                  `protobuf:"varint,6,opt,name=totalWeight,proto3" json:"totalWeight,omitempty" bson:"totalWeight"`                                                               // @gotags: bson:"totalWeight"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BoosterSheet) Reset() {
	*x = BoosterSheet{}
	mi := &file_booster_booster_sheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoosterSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoosterSheet) ProtoMessage() {}

func (x *BoosterSheet) ProtoReflect() protoreflect.Message {
	mi := &file_booster_booster_sheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoosterSheet.ProtoReflect.Descriptor instead.
func (*BoosterSheet) Descriptor() ([]byte, []int) {
	return file_booster_booster_sheet_proto_rawDescGZIP(), []int{0}
}

func (x *BoosterSheet) GetAllowDuplicates() bool {
	if x != nil {
		return x.AllowDuplicates
	}
	return false
}

func (x *BoosterSheet) GetBalanceColors() bool {
	if x != nil {
		return x.BalanceColors
	}
	return false
}

func (x *BoosterSheet) GetCards() map[string]int64 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *BoosterSheet) GetFoil() bool {
	if x != nil {
		return x.Foil
	}
	return false
}

func (x *BoosterSheet) GetFixed() bool {
	if x != nil {
		return x.Fixed
	}
	return false
}

func (x *BoosterSheet) GetTotalWeight() int64 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

var File_booster_booster_sheet_proto protoreflect.FileDescriptor

const file_booster_booster_sheet_proto_rawDesc = "" +
	"\n" +
	"\x1bbooster/booster_sheet.proto\x12\abooster\"\x9c\x02\n" +
	"\fBoosterSheet\x12(\n" +
	"\x0fallowDuplicates\x18\x01 \x01(\bR\x0fallowDuplicates\x12$\n" +
	"\rbalanceColors\x18\x02 \x01(\bR\rbalanceColors\x126\n" +
	"\x05cards\x18\x03 \x03(\v2 .booster.BoosterSheet.CardsEntryR\x05cards\x12\x12\n" +
	"\x04foil\x18\x04 \x01(\bR\x04foil\x12\x14\n" +
	"\x05fixed\x18\x05 \x01(\bR\x05fixed\x12 \n" +
	"\vtotalWeight\x18\x06 \x01(\x03R\vtotalWeight\x1a8\n" +
	"\n" +
	"CardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B.Z,github.com/stevezaluk/mtgjson-models/boosterb\x06proto3"

var (
	file_booster_booster_sheet_proto_rawDescOnce sync.Once
	file_booster_booster_sheet_proto_rawDescData []byte
)

func file_booster_booster_sheet_proto_rawDescGZIP() []byte {
	file_booster_booster_sheet_proto_rawDescOnce.Do(func() {
		file_booster_booster_sheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booster_booster_sheet_proto_rawDesc), len(file_booster_booster_sheet_proto_rawDesc)))
	})
	return file_booster_booster_sheet_proto_rawDescData
}

var file_booster_booster_sheet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booster_booster_sheet_proto_goTypes = []any{
	(*BoosterSheet)(nil), // 0: booster.BoosterSheet
	nil,                  // 1: booster.BoosterSheet.CardsEntry
}
var file_booster_booster_sheet_proto_depIdxs = []int32{
	1, // 0: booster.BoosterSheet.cards:type_name -> booster.BoosterSheet.CardsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_booster_booster_sheet_proto_init() }
func file_booster_booster_sheet_proto_init() {
	if File_booster_booster_sheet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booster_booster_sheet_proto_rawDesc), len(file_booster_booster_sheet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booster_booster_sheet_proto_goTypes,
		DependencyIndexes: file_booster_booster_sheet_proto_depIdxs,
		MessageInfos:      file_booster_booster_sheet_proto_msgTypes,
	}.Build()
	File_booster_booster_sheet_proto = out.File
	file_booster_booster_sheet_proto_goTypes = nil
	file_booster_booster_sheet_proto_depIdxs = nil
}
