// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: booster/booster.proto

package booster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoosterPack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      map[string]int64       `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value" bson:"contents"` // @gotags: bson:"contents"
	Weight        int64                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty" bson:"weight"`                                                                               // @gotags: bson:"weight"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoosterPack) Reset() {
	*x = BoosterPack{}
	mi := &file_booster_booster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoosterPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoosterPack) ProtoMessage() {}

func (x *BoosterPack) ProtoReflect() protoreflect.Message {
	mi := &file_booster_booster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoosterPack.ProtoReflect.Descriptor instead.
func (*BoosterPack) Descriptor() ([]byte, []int) {
	return file_booster_booster_proto_rawDescGZIP(), []int{0}
}

func (x *BoosterPack) GetContents() map[string]int64 {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *BoosterPack) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_booster_booster_proto protoreflect.FileDescriptor

const file_booster_booster_proto_rawDesc = "" +
	"\n" +
	"\x15booster/booster.proto\x12\abooster\"\xa2\x01\n" +
	"\vBoosterPack\x12>\n" +
	"\bcontents\x18\x01 \x03(\v2\".booster.BoosterPack.ContentsEntryR\bcontents\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x03R\x06weight\x1a;\n" +
	"\rContentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B.Z,github.com/stevezaluk/mtgjson-models/boosterb\x06proto3"

var (
	file_booster_booster_proto_rawDescOnce sync.Once
	file_booster_booster_proto_rawDescData []byte
)

func file_booster_booster_proto_rawDescGZIP() []byte {
	file_booster_booster_proto_rawDescOnce.Do(func() {
		file_booster_booster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booster_booster_proto_rawDesc), len(file_booster_booster_proto_rawDesc)))
	})
	return file_booster_booster_proto_rawDescData
}

var file_booster_booster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booster_booster_proto_goTypes = []any{
	(*BoosterPack)(nil), // 0: booster.BoosterPack
	nil,                 // 1: booster.BoosterPack.ContentsEntry
}
var file_booster_booster_proto_depIdxs = []int32{
	1, // 0: booster.BoosterPack.contents:type_name -> booster.BoosterPack.ContentsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_booster_booster_proto_init() }
func file_booster_booster_proto_init() {
	if File_booster_booster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booster_booster_proto_rawDesc), len(file_booster_booster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booster_booster_proto_goTypes,
		DependencyIndexes: file_booster_booster_proto_depIdxs,
		MessageInfos:      file_booster_booster_proto_msgTypes,
	}.Build()
	File_booster_booster_proto = out.File
	file_booster_booster_proto_goTypes = nil
	file_booster_booster_proto_depIdxs = nil
}
