// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.6.1
// source: booster/booster.proto

package booster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoosterPack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contents map[string]int64 `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" bson:"contents"` // @gotags: bson:"contents"
	Weight   int64            `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty" bson:"weight"`                                                                                             // @gotags: bson:"weight"
}

func (x *BoosterPack) Reset() {
	*x = BoosterPack{}
	mi := &file_booster_booster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoosterPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoosterPack) ProtoMessage() {}

func (x *BoosterPack) ProtoReflect() protoreflect.Message {
	mi := &file_booster_booster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoosterPack.ProtoReflect.Descriptor instead.
func (*BoosterPack) Descriptor() ([]byte, []int) {
	return file_booster_booster_proto_rawDescGZIP(), []int{0}
}

func (x *BoosterPack) GetContents() map[string]int64 {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *BoosterPack) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_booster_booster_proto protoreflect.FileDescriptor

var file_booster_booster_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x65, 0x72,
	0x22, 0xa2, 0x01, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b,
	0x12, 0x3e, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x6f, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x3b, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x76, 0x65, 0x7a, 0x61, 0x6c, 0x75, 0x6b, 0x2f, 0x6d,
	0x74, 0x67, 0x6a, 0x73, 0x6f, 0x6e, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x62, 0x6f,
	0x6f, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_booster_booster_proto_rawDescOnce sync.Once
	file_booster_booster_proto_rawDescData = file_booster_booster_proto_rawDesc
)

func file_booster_booster_proto_rawDescGZIP() []byte {
	file_booster_booster_proto_rawDescOnce.Do(func() {
		file_booster_booster_proto_rawDescData = protoimpl.X.CompressGZIP(file_booster_booster_proto_rawDescData)
	})
	return file_booster_booster_proto_rawDescData
}

var file_booster_booster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booster_booster_proto_goTypes = []any{
	(*BoosterPack)(nil), // 0: booster.BoosterPack
	nil,                 // 1: booster.BoosterPack.ContentsEntry
}
var file_booster_booster_proto_depIdxs = []int32{
	1, // 0: booster.BoosterPack.contents:type_name -> booster.BoosterPack.ContentsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_booster_booster_proto_init() }
func file_booster_booster_proto_init() {
	if File_booster_booster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_booster_booster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booster_booster_proto_goTypes,
		DependencyIndexes: file_booster_booster_proto_depIdxs,
		MessageInfos:      file_booster_booster_proto_msgTypes,
	}.Build()
	File_booster_booster_proto = out.File
	file_booster_booster_proto_rawDesc = nil
	file_booster_booster_proto_goTypes = nil
	file_booster_booster_proto_depIdxs = nil
}
