// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.6.1
// source: meta/card_rulings.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardRulings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *CardRulings) Reset() {
	*x = CardRulings{}
	mi := &file_meta_card_rulings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRulings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRulings) ProtoMessage() {}

func (x *CardRulings) ProtoReflect() protoreflect.Message {
	mi := &file_meta_card_rulings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRulings.ProtoReflect.Descriptor instead.
func (*CardRulings) Descriptor() ([]byte, []int) {
	return file_meta_card_rulings_proto_rawDescGZIP(), []int{0}
}

func (x *CardRulings) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CardRulings) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_meta_card_rulings_proto protoreflect.FileDescriptor

var file_meta_card_rulings_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x72, 0x75, 0x6c, 0x69,
	0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22,
	0x35, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x64, 0x52, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x6d, 0x74, 0x67, 0x6a,
	0x73, 0x6f, 0x6e, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meta_card_rulings_proto_rawDescOnce sync.Once
	file_meta_card_rulings_proto_rawDescData = file_meta_card_rulings_proto_rawDesc
)

func file_meta_card_rulings_proto_rawDescGZIP() []byte {
	file_meta_card_rulings_proto_rawDescOnce.Do(func() {
		file_meta_card_rulings_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_card_rulings_proto_rawDescData)
	})
	return file_meta_card_rulings_proto_rawDescData
}

var file_meta_card_rulings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_card_rulings_proto_goTypes = []any{
	(*CardRulings)(nil), // 0: meta.CardRulings
}
var file_meta_card_rulings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_card_rulings_proto_init() }
func file_meta_card_rulings_proto_init() {
	if File_meta_card_rulings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_card_rulings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_card_rulings_proto_goTypes,
		DependencyIndexes: file_meta_card_rulings_proto_depIdxs,
		MessageInfos:      file_meta_card_rulings_proto_msgTypes,
	}.Build()
	File_meta_card_rulings_proto = out.File
	file_meta_card_rulings_proto_rawDesc = nil
	file_meta_card_rulings_proto_goTypes = nil
	file_meta_card_rulings_proto_depIdxs = nil
}
