// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: meta/foreign_data.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForeignData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FaceName      string                 `protobuf:"bytes,1,opt,name=faceName,proto3" json:"faceName,omitempty" bson:"faceName"`       // @gotags: bson:"faceName"
	FlavorText    string                 `protobuf:"bytes,2,opt,name=flavorText,proto3" json:"flavorText,omitempty" bson:"flavorText"`   // @gotags: bson:"flavorText"
	Identifiers   *CardIdentifiers       `protobuf:"bytes,3,opt,name=identifiers,proto3" json:"identifiers,omitempty" bson:"identifiers"` // @gotags: bson:"identifiers"
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty" bson:"language"`       // @gotags: bson:"language"
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty" bson:"name"`               // @gotags: bson:"name"
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty" bson:"text"`               // @gotags: bson:"text"
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty" bson:"type"`               // @gotags: bson:"type"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForeignData) Reset() {
	*x = ForeignData{}
	mi := &file_meta_foreign_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForeignData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignData) ProtoMessage() {}

func (x *ForeignData) ProtoReflect() protoreflect.Message {
	mi := &file_meta_foreign_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignData.ProtoReflect.Descriptor instead.
func (*ForeignData) Descriptor() ([]byte, []int) {
	return file_meta_foreign_data_proto_rawDescGZIP(), []int{0}
}

func (x *ForeignData) GetFaceName() string {
	if x != nil {
		return x.FaceName
	}
	return ""
}

func (x *ForeignData) GetFlavorText() string {
	if x != nil {
		return x.FlavorText
	}
	return ""
}

func (x *ForeignData) GetIdentifiers() *CardIdentifiers {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

func (x *ForeignData) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ForeignData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ForeignData) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ForeignData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_meta_foreign_data_proto protoreflect.FileDescriptor

const file_meta_foreign_data_proto_rawDesc = "" +
	"\n" +
	"\x17meta/foreign_data.proto\x12\x04meta\x1a\x16meta/identifiers.proto\"\xda\x01\n" +
	"\vForeignData\x12\x1a\n" +
	"\bfaceName\x18\x01 \x01(\tR\bfaceName\x12\x1e\n" +
	"\n" +
	"flavorText\x18\x02 \x01(\tR\n" +
	"flavorText\x127\n" +
	"\videntifiers\x18\x03 \x01(\v2\x15.meta.CardIdentifiersR\videntifiers\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04typeB+Z)github.com/stevezaluk/mtgjson-models/metab\x06proto3"

var (
	file_meta_foreign_data_proto_rawDescOnce sync.Once
	file_meta_foreign_data_proto_rawDescData []byte
)

func file_meta_foreign_data_proto_rawDescGZIP() []byte {
	file_meta_foreign_data_proto_rawDescOnce.Do(func() {
		file_meta_foreign_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_foreign_data_proto_rawDesc), len(file_meta_foreign_data_proto_rawDesc)))
	})
	return file_meta_foreign_data_proto_rawDescData
}

var file_meta_foreign_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_foreign_data_proto_goTypes = []any{
	(*ForeignData)(nil),     // 0: meta.ForeignData
	(*CardIdentifiers)(nil), // 1: meta.CardIdentifiers
}
var file_meta_foreign_data_proto_depIdxs = []int32{
	1, // 0: meta.ForeignData.identifiers:type_name -> meta.CardIdentifiers
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meta_foreign_data_proto_init() }
func file_meta_foreign_data_proto_init() {
	if File_meta_foreign_data_proto != nil {
		return
	}
	file_meta_identifiers_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_foreign_data_proto_rawDesc), len(file_meta_foreign_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_foreign_data_proto_goTypes,
		DependencyIndexes: file_meta_foreign_data_proto_depIdxs,
		MessageInfos:      file_meta_foreign_data_proto_msgTypes,
	}.Build()
	File_meta_foreign_data_proto = out.File
	file_meta_foreign_data_proto_goTypes = nil
	file_meta_foreign_data_proto_depIdxs = nil
}
