// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: meta/leadership.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeadershipSkills struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brawl         bool                   `protobuf:"varint,1,opt,name=brawl,proto3" json:"brawl,omitempty" bson:"brawl"`             // @gotags: bson:"brawl"
	Commander     bool                   `protobuf:"varint,2,opt,name=commander,proto3" json:"commander,omitempty" bson:"commander"`     // @gotags: bson:"commander"
	Oathbreaker   bool                   `protobuf:"varint,3,opt,name=oathbreaker,proto3" json:"oathbreaker,omitempty" bson:"oathbreaker"` // @gotags: bson:"oathbreaker"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadershipSkills) Reset() {
	*x = LeadershipSkills{}
	mi := &file_meta_leadership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadershipSkills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadershipSkills) ProtoMessage() {}

func (x *LeadershipSkills) ProtoReflect() protoreflect.Message {
	mi := &file_meta_leadership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadershipSkills.ProtoReflect.Descriptor instead.
func (*LeadershipSkills) Descriptor() ([]byte, []int) {
	return file_meta_leadership_proto_rawDescGZIP(), []int{0}
}

func (x *LeadershipSkills) GetBrawl() bool {
	if x != nil {
		return x.Brawl
	}
	return false
}

func (x *LeadershipSkills) GetCommander() bool {
	if x != nil {
		return x.Commander
	}
	return false
}

func (x *LeadershipSkills) GetOathbreaker() bool {
	if x != nil {
		return x.Oathbreaker
	}
	return false
}

var File_meta_leadership_proto protoreflect.FileDescriptor

const file_meta_leadership_proto_rawDesc = "" +
	"\n" +
	"\x15meta/leadership.proto\x12\x04meta\"h\n" +
	"\x10LeadershipSkills\x12\x14\n" +
	"\x05brawl\x18\x01 \x01(\bR\x05brawl\x12\x1c\n" +
	"\tcommander\x18\x02 \x01(\bR\tcommander\x12 \n" +
	"\voathbreaker\x18\x03 \x01(\bR\voathbreakerB+Z)github.com/stevezaluk/mtgjson-models/metab\x06proto3"

var (
	file_meta_leadership_proto_rawDescOnce sync.Once
	file_meta_leadership_proto_rawDescData []byte
)

func file_meta_leadership_proto_rawDescGZIP() []byte {
	file_meta_leadership_proto_rawDescOnce.Do(func() {
		file_meta_leadership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_leadership_proto_rawDesc), len(file_meta_leadership_proto_rawDesc)))
	})
	return file_meta_leadership_proto_rawDescData
}

var file_meta_leadership_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_leadership_proto_goTypes = []any{
	(*LeadershipSkills)(nil), // 0: meta.LeadershipSkills
}
var file_meta_leadership_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_leadership_proto_init() }
func file_meta_leadership_proto_init() {
	if File_meta_leadership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_leadership_proto_rawDesc), len(file_meta_leadership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_leadership_proto_goTypes,
		DependencyIndexes: file_meta_leadership_proto_depIdxs,
		MessageInfos:      file_meta_leadership_proto_msgTypes,
	}.Build()
	File_meta_leadership_proto = out.File
	file_meta_leadership_proto_goTypes = nil
	file_meta_leadership_proto_depIdxs = nil
}
