// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.6.1
// source: meta/leadership.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeadershipSkills struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brawl       bool `protobuf:"varint,1,opt,name=brawl,proto3" json:"brawl,omitempty"`
	Commander   bool `protobuf:"varint,2,opt,name=commander,proto3" json:"commander,omitempty"`
	Oathbreaker bool `protobuf:"varint,3,opt,name=oathbreaker,proto3" json:"oathbreaker,omitempty"`
}

func (x *LeadershipSkills) Reset() {
	*x = LeadershipSkills{}
	mi := &file_meta_leadership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadershipSkills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadershipSkills) ProtoMessage() {}

func (x *LeadershipSkills) ProtoReflect() protoreflect.Message {
	mi := &file_meta_leadership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadershipSkills.ProtoReflect.Descriptor instead.
func (*LeadershipSkills) Descriptor() ([]byte, []int) {
	return file_meta_leadership_proto_rawDescGZIP(), []int{0}
}

func (x *LeadershipSkills) GetBrawl() bool {
	if x != nil {
		return x.Brawl
	}
	return false
}

func (x *LeadershipSkills) GetCommander() bool {
	if x != nil {
		return x.Commander
	}
	return false
}

func (x *LeadershipSkills) GetOathbreaker() bool {
	if x != nil {
		return x.Oathbreaker
	}
	return false
}

var File_meta_leadership_proto protoreflect.FileDescriptor

var file_meta_leadership_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x68, 0x0a,
	0x10, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x61, 0x74, 0x68, 0x62, 0x72, 0x65,
	0x61, 0x6b, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6f, 0x61, 0x74, 0x68,
	0x62, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x76, 0x65, 0x7a, 0x61, 0x6c, 0x75, 0x6b,
	0x2f, 0x6d, 0x74, 0x67, 0x6a, 0x73, 0x6f, 0x6e, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x6d, 0x65, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meta_leadership_proto_rawDescOnce sync.Once
	file_meta_leadership_proto_rawDescData = file_meta_leadership_proto_rawDesc
)

func file_meta_leadership_proto_rawDescGZIP() []byte {
	file_meta_leadership_proto_rawDescOnce.Do(func() {
		file_meta_leadership_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_leadership_proto_rawDescData)
	})
	return file_meta_leadership_proto_rawDescData
}

var file_meta_leadership_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_leadership_proto_goTypes = []any{
	(*LeadershipSkills)(nil), // 0: meta.LeadershipSkills
}
var file_meta_leadership_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_leadership_proto_init() }
func file_meta_leadership_proto_init() {
	if File_meta_leadership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_leadership_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_leadership_proto_goTypes,
		DependencyIndexes: file_meta_leadership_proto_depIdxs,
		MessageInfos:      file_meta_leadership_proto_msgTypes,
	}.Build()
	File_meta_leadership_proto = out.File
	file_meta_leadership_proto_rawDesc = nil
	file_meta_leadership_proto_goTypes = nil
	file_meta_leadership_proto_depIdxs = nil
}
