// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: meta/mtgjson_api.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MTGJSONAPIMeta - Meta data defined at the top of a MTGJSON structure, used to track ownership
type MTGJSONAPIMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreationDate  string                 `protobuf:"bytes,1,opt,name=creationDate,proto3" json:"creationDate,omitempty" bson:"creationDate"` // @gotags: bson:"creationDate"
	ModifiedDate  string                 `protobuf:"bytes,2,opt,name=modifiedDate,proto3" json:"modifiedDate,omitempty" bson:"modifiedDate"` // @gotags: bson:"modifiedDate"
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty" bson:"owner"`               // @gotags: bson:"owner"
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty" bson:"type"`                 // @gotags: bson:"type"
	Subtype       string                 `protobuf:"bytes,5,opt,name=subtype,proto3" json:"subtype,omitempty" bson:"subtype"`           // @gotags: bson:"subtype"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MTGJSONAPIMeta) Reset() {
	*x = MTGJSONAPIMeta{}
	mi := &file_meta_mtgjson_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MTGJSONAPIMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTGJSONAPIMeta) ProtoMessage() {}

func (x *MTGJSONAPIMeta) ProtoReflect() protoreflect.Message {
	mi := &file_meta_mtgjson_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTGJSONAPIMeta.ProtoReflect.Descriptor instead.
func (*MTGJSONAPIMeta) Descriptor() ([]byte, []int) {
	return file_meta_mtgjson_api_proto_rawDescGZIP(), []int{0}
}

func (x *MTGJSONAPIMeta) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *MTGJSONAPIMeta) GetModifiedDate() string {
	if x != nil {
		return x.ModifiedDate
	}
	return ""
}

func (x *MTGJSONAPIMeta) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MTGJSONAPIMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MTGJSONAPIMeta) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

var File_meta_mtgjson_api_proto protoreflect.FileDescriptor

const file_meta_mtgjson_api_proto_rawDesc = "" +
	"\n" +
	"\x16meta/mtgjson_api.proto\x12\x04meta\"\x9c\x01\n" +
	"\x0eMTGJSONAPIMeta\x12\"\n" +
	"\fcreationDate\x18\x01 \x01(\tR\fcreationDate\x12\"\n" +
	"\fmodifiedDate\x18\x02 \x01(\tR\fmodifiedDate\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\asubtype\x18\x05 \x01(\tR\asubtypeB+Z)github.com/stevezaluk/mtgjson-models/metab\x06proto3"

var (
	file_meta_mtgjson_api_proto_rawDescOnce sync.Once
	file_meta_mtgjson_api_proto_rawDescData []byte
)

func file_meta_mtgjson_api_proto_rawDescGZIP() []byte {
	file_meta_mtgjson_api_proto_rawDescOnce.Do(func() {
		file_meta_mtgjson_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_mtgjson_api_proto_rawDesc), len(file_meta_mtgjson_api_proto_rawDesc)))
	})
	return file_meta_mtgjson_api_proto_rawDescData
}

var file_meta_mtgjson_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_mtgjson_api_proto_goTypes = []any{
	(*MTGJSONAPIMeta)(nil), // 0: meta.MTGJSONAPIMeta
}
var file_meta_mtgjson_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_mtgjson_api_proto_init() }
func file_meta_mtgjson_api_proto_init() {
	if File_meta_mtgjson_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_mtgjson_api_proto_rawDesc), len(file_meta_mtgjson_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_mtgjson_api_proto_goTypes,
		DependencyIndexes: file_meta_mtgjson_api_proto_depIdxs,
		MessageInfos:      file_meta_mtgjson_api_proto_msgTypes,
	}.Build()
	File_meta_mtgjson_api_proto = out.File
	file_meta_mtgjson_api_proto_goTypes = nil
	file_meta_mtgjson_api_proto_depIdxs = nil
}
