// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: meta/purchase_urls.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurchaseUrls struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CardKingdom       string                 `protobuf:"bytes,1,opt,name=cardKingdom,proto3" json:"cardKingdom,omitempty" bson:"cardKingdom"`             // @gotags: bson:"cardKingdom"
	CardKingdomEtched string                 `protobuf:"bytes,2,opt,name=cardKingdomEtched,proto3" json:"cardKingdomEtched,omitempty" bson:"cardKingdomEtched"` // @gotags: bson:"cardKingdomEtched"
	CardKingdomFoil   string                 `protobuf:"bytes,3,opt,name=cardKingdomFoil,proto3" json:"cardKingdomFoil,omitempty" bson:"cardKingdomFoil"`     // @gotags: bson:"cardKingdomFoil"
	Cardmarket        string                 `protobuf:"bytes,4,opt,name=cardmarket,proto3" json:"cardmarket,omitempty" bson:"cardmarket"`               // @gotags: bson:"cardmarket"
	Tcgplayer         string                 `protobuf:"bytes,5,opt,name=tcgplayer,proto3" json:"tcgplayer,omitempty" bson:"tcgplayer"`                 // @gotags: bson:"tcgplayer"
	TcgplayerEtched   string                 `protobuf:"bytes,6,opt,name=tcgplayerEtched,proto3" json:"tcgplayerEtched,omitempty" bson:"tcgplayerEtched"`     // @gotags: bson:"tcgplayerEtched"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PurchaseUrls) Reset() {
	*x = PurchaseUrls{}
	mi := &file_meta_purchase_urls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseUrls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseUrls) ProtoMessage() {}

func (x *PurchaseUrls) ProtoReflect() protoreflect.Message {
	mi := &file_meta_purchase_urls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseUrls.ProtoReflect.Descriptor instead.
func (*PurchaseUrls) Descriptor() ([]byte, []int) {
	return file_meta_purchase_urls_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseUrls) GetCardKingdom() string {
	if x != nil {
		return x.CardKingdom
	}
	return ""
}

func (x *PurchaseUrls) GetCardKingdomEtched() string {
	if x != nil {
		return x.CardKingdomEtched
	}
	return ""
}

func (x *PurchaseUrls) GetCardKingdomFoil() string {
	if x != nil {
		return x.CardKingdomFoil
	}
	return ""
}

func (x *PurchaseUrls) GetCardmarket() string {
	if x != nil {
		return x.Cardmarket
	}
	return ""
}

func (x *PurchaseUrls) GetTcgplayer() string {
	if x != nil {
		return x.Tcgplayer
	}
	return ""
}

func (x *PurchaseUrls) GetTcgplayerEtched() string {
	if x != nil {
		return x.TcgplayerEtched
	}
	return ""
}

var File_meta_purchase_urls_proto protoreflect.FileDescriptor

const file_meta_purchase_urls_proto_rawDesc = "" +
	"\n" +
	"\x18meta/purchase_urls.proto\x12\x04meta\"\xf0\x01\n" +
	"\fPurchaseUrls\x12 \n" +
	"\vcardKingdom\x18\x01 \x01(\tR\vcardKingdom\x12,\n" +
	"\x11cardKingdomEtched\x18\x02 \x01(\tR\x11cardKingdomEtched\x12(\n" +
	"\x0fcardKingdomFoil\x18\x03 \x01(\tR\x0fcardKingdomFoil\x12\x1e\n" +
	"\n" +
	"cardmarket\x18\x04 \x01(\tR\n" +
	"cardmarket\x12\x1c\n" +
	"\ttcgplayer\x18\x05 \x01(\tR\ttcgplayer\x12(\n" +
	"\x0ftcgplayerEtched\x18\x06 \x01(\tR\x0ftcgplayerEtchedB+Z)github.com/stevezaluk/mtgjson-models/metab\x06proto3"

var (
	file_meta_purchase_urls_proto_rawDescOnce sync.Once
	file_meta_purchase_urls_proto_rawDescData []byte
)

func file_meta_purchase_urls_proto_rawDescGZIP() []byte {
	file_meta_purchase_urls_proto_rawDescOnce.Do(func() {
		file_meta_purchase_urls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_purchase_urls_proto_rawDesc), len(file_meta_purchase_urls_proto_rawDesc)))
	})
	return file_meta_purchase_urls_proto_rawDescData
}

var file_meta_purchase_urls_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_purchase_urls_proto_goTypes = []any{
	(*PurchaseUrls)(nil), // 0: meta.PurchaseUrls
}
var file_meta_purchase_urls_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_purchase_urls_proto_init() }
func file_meta_purchase_urls_proto_init() {
	if File_meta_purchase_urls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_purchase_urls_proto_rawDesc), len(file_meta_purchase_urls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_purchase_urls_proto_goTypes,
		DependencyIndexes: file_meta_purchase_urls_proto_depIdxs,
		MessageInfos:      file_meta_purchase_urls_proto_msgTypes,
	}.Build()
	File_meta_purchase_urls_proto = out.File
	file_meta_purchase_urls_proto_goTypes = nil
	file_meta_purchase_urls_proto_depIdxs = nil
}
