// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: meta/source_products.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceProducts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etched        []string               `protobuf:"bytes,1,rep,name=etched,proto3" json:"etched,omitempty" bson:"etched"`   // @gotags: bson:"etched"
	Foil          []string               `protobuf:"bytes,2,rep,name=foil,proto3" json:"foil,omitempty" bson:"foil"`       // @gotags: bson:"foil"
	Nonfoil       []string               `protobuf:"bytes,3,rep,name=nonfoil,proto3" json:"nonfoil,omitempty" bson:"nonfoil"` // @gotags: bson:"nonfoil"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceProducts) Reset() {
	*x = SourceProducts{}
	mi := &file_meta_source_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceProducts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceProducts) ProtoMessage() {}

func (x *SourceProducts) ProtoReflect() protoreflect.Message {
	mi := &file_meta_source_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceProducts.ProtoReflect.Descriptor instead.
func (*SourceProducts) Descriptor() ([]byte, []int) {
	return file_meta_source_products_proto_rawDescGZIP(), []int{0}
}

func (x *SourceProducts) GetEtched() []string {
	if x != nil {
		return x.Etched
	}
	return nil
}

func (x *SourceProducts) GetFoil() []string {
	if x != nil {
		return x.Foil
	}
	return nil
}

func (x *SourceProducts) GetNonfoil() []string {
	if x != nil {
		return x.Nonfoil
	}
	return nil
}

var File_meta_source_products_proto protoreflect.FileDescriptor

const file_meta_source_products_proto_rawDesc = "" +
	"\n" +
	"\x1ameta/source_products.proto\x12\x04meta\"V\n" +
	"\x0eSourceProducts\x12\x16\n" +
	"\x06etched\x18\x01 \x03(\tR\x06etched\x12\x12\n" +
	"\x04foil\x18\x02 \x03(\tR\x04foil\x12\x18\n" +
	"\anonfoil\x18\x03 \x03(\tR\anonfoilB+Z)github.com/stevezaluk/mtgjson-models/metab\x06proto3"

var (
	file_meta_source_products_proto_rawDescOnce sync.Once
	file_meta_source_products_proto_rawDescData []byte
)

func file_meta_source_products_proto_rawDescGZIP() []byte {
	file_meta_source_products_proto_rawDescOnce.Do(func() {
		file_meta_source_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_source_products_proto_rawDesc), len(file_meta_source_products_proto_rawDesc)))
	})
	return file_meta_source_products_proto_rawDescData
}

var file_meta_source_products_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_source_products_proto_goTypes = []any{
	(*SourceProducts)(nil), // 0: meta.SourceProducts
}
var file_meta_source_products_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_source_products_proto_init() }
func file_meta_source_products_proto_init() {
	if File_meta_source_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_source_products_proto_rawDesc), len(file_meta_source_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_source_products_proto_goTypes,
		DependencyIndexes: file_meta_source_products_proto_depIdxs,
		MessageInfos:      file_meta_source_products_proto_msgTypes,
	}.Build()
	File_meta_source_products_proto = out.File
	file_meta_source_products_proto_goTypes = nil
	file_meta_source_products_proto_depIdxs = nil
}
