// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: deck/deck.proto

package deck

import (
	card "github.com/stevezaluk/mtgjson-models/card"
	meta "github.com/stevezaluk/mtgjson-models/meta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deck - Represents an MTGJSON deck
//
// See here for more info: https://mtgjson.com/data-models/deck
//
// This model has been changed slightly from the original model to seperate out lists for
// both the card ids and for cards themselves. This way we can store just the ID's in the database
// and fill the contents field before it gets returned to the user
type Deck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" bson:"name"`                     // @gotags: bson:"name"
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty" bson:"code"`                     // @gotags: bson:"code"
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty" bson:"type"`                     // @gotags: bson:"type"
	ReleaseDate    string                 `protobuf:"bytes,4,opt,name=releaseDate,proto3" json:"releaseDate,omitempty" bson:"releaseDate"`       // @gotags: bson:"releaseDate"
	ContentIds     *DeckContentIds        `protobuf:"bytes,5,opt,name=contentIds,proto3" json:"contentIds,omitempty" bson:"contentIds"`         // @gotags: bson:"contentIds"
	Contents       *DeckContents          `protobuf:"bytes,6,opt,name=contents,proto3" json:"contents,omitempty" bson:"contents"`             // @gotags: bson:"contents"
	MtgjsonApiMeta *meta.MTGJSONAPIMeta   `protobuf:"bytes,7,opt,name=mtgjsonApiMeta,proto3" json:"mtgjsonApiMeta,omitempty" bson:"mtgjsonApiMeta"` // @gotags: bson:"mtgjsonApiMeta"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Deck) Reset() {
	*x = Deck{}
	mi := &file_deck_deck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deck) ProtoMessage() {}

func (x *Deck) ProtoReflect() protoreflect.Message {
	mi := &file_deck_deck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deck.ProtoReflect.Descriptor instead.
func (*Deck) Descriptor() ([]byte, []int) {
	return file_deck_deck_proto_rawDescGZIP(), []int{0}
}

func (x *Deck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deck) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Deck) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Deck) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Deck) GetContentIds() *DeckContentIds {
	if x != nil {
		return x.ContentIds
	}
	return nil
}

func (x *Deck) GetContents() *DeckContents {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *Deck) GetMtgjsonApiMeta() *meta.MTGJSONAPIMeta {
	if x != nil {
		return x.MtgjsonApiMeta
	}
	return nil
}

// DeckContentIds - Represents the MTGJSON v4 ID's that make up a deck
type DeckContentIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainBoard     []string               `protobuf:"bytes,1,rep,name=mainBoard,proto3" json:"mainBoard,omitempty" bson:"mainBoard"` // @gotags: bson:"mainBoard"
	SideBoard     []string               `protobuf:"bytes,2,rep,name=sideBoard,proto3" json:"sideBoard,omitempty" bson:"sideBoard"` // @gotags: bson:"sideBoard"
	Commander     []string               `protobuf:"bytes,3,rep,name=commander,proto3" json:"commander,omitempty" bson:"commander"` // @gotags: bson:"commander"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckContentIds) Reset() {
	*x = DeckContentIds{}
	mi := &file_deck_deck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckContentIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckContentIds) ProtoMessage() {}

func (x *DeckContentIds) ProtoReflect() protoreflect.Message {
	mi := &file_deck_deck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckContentIds.ProtoReflect.Descriptor instead.
func (*DeckContentIds) Descriptor() ([]byte, []int) {
	return file_deck_deck_proto_rawDescGZIP(), []int{1}
}

func (x *DeckContentIds) GetMainBoard() []string {
	if x != nil {
		return x.MainBoard
	}
	return nil
}

func (x *DeckContentIds) GetSideBoard() []string {
	if x != nil {
		return x.SideBoard
	}
	return nil
}

func (x *DeckContentIds) GetCommander() []string {
	if x != nil {
		return x.Commander
	}
	return nil
}

// DeckContents - Represents the MTGJSON Cards of the decks and its boards
type DeckContents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainBoard     []*card.CardSet        `protobuf:"bytes,1,rep,name=mainBoard,proto3" json:"mainBoard,omitempty" bson:"mainBoard"` // @gotags: bson:"mainBoard"
	SideBoard     []*card.CardSet        `protobuf:"bytes,2,rep,name=sideBoard,proto3" json:"sideBoard,omitempty" bson:"sideBoard"` // @gotags: bson:"sideBoard"
	Commander     []*card.CardSet        `protobuf:"bytes,3,rep,name=commander,proto3" json:"commander,omitempty" bson:"commander"` // @gotags: bson:"commander"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckContents) Reset() {
	*x = DeckContents{}
	mi := &file_deck_deck_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckContents) ProtoMessage() {}

func (x *DeckContents) ProtoReflect() protoreflect.Message {
	mi := &file_deck_deck_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckContents.ProtoReflect.Descriptor instead.
func (*DeckContents) Descriptor() ([]byte, []int) {
	return file_deck_deck_proto_rawDescGZIP(), []int{2}
}

func (x *DeckContents) GetMainBoard() []*card.CardSet {
	if x != nil {
		return x.MainBoard
	}
	return nil
}

func (x *DeckContents) GetSideBoard() []*card.CardSet {
	if x != nil {
		return x.SideBoard
	}
	return nil
}

func (x *DeckContents) GetCommander() []*card.CardSet {
	if x != nil {
		return x.Commander
	}
	return nil
}

var File_deck_deck_proto protoreflect.FileDescriptor

const file_deck_deck_proto_rawDesc = "" +
	"\n" +
	"\x0fdeck/deck.proto\x12\x04deck\x1a\x13card/card_set.proto\x1a\x16meta/mtgjson_api.proto\"\x88\x02\n" +
	"\x04Deck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vreleaseDate\x18\x04 \x01(\tR\vreleaseDate\x124\n" +
	"\n" +
	"contentIds\x18\x05 \x01(\v2\x14.deck.DeckContentIdsR\n" +
	"contentIds\x12.\n" +
	"\bcontents\x18\x06 \x01(\v2\x12.deck.DeckContentsR\bcontents\x12<\n" +
	"\x0emtgjsonApiMeta\x18\a \x01(\v2\x14.meta.MTGJSONAPIMetaR\x0emtgjsonApiMeta\"j\n" +
	"\x0eDeckContentIds\x12\x1c\n" +
	"\tmainBoard\x18\x01 \x03(\tR\tmainBoard\x12\x1c\n" +
	"\tsideBoard\x18\x02 \x03(\tR\tsideBoard\x12\x1c\n" +
	"\tcommander\x18\x03 \x03(\tR\tcommander\"\x95\x01\n" +
	"\fDeckContents\x12+\n" +
	"\tmainBoard\x18\x01 \x03(\v2\r.card.CardSetR\tmainBoard\x12+\n" +
	"\tsideBoard\x18\x02 \x03(\v2\r.card.CardSetR\tsideBoard\x12+\n" +
	"\tcommander\x18\x03 \x03(\v2\r.card.CardSetR\tcommanderB+Z)github.com/stevezaluk/mtgjson-models/deckb\x06proto3"

var (
	file_deck_deck_proto_rawDescOnce sync.Once
	file_deck_deck_proto_rawDescData []byte
)

func file_deck_deck_proto_rawDescGZIP() []byte {
	file_deck_deck_proto_rawDescOnce.Do(func() {
		file_deck_deck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deck_deck_proto_rawDesc), len(file_deck_deck_proto_rawDesc)))
	})
	return file_deck_deck_proto_rawDescData
}

var file_deck_deck_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_deck_deck_proto_goTypes = []any{
	(*Deck)(nil),                // 0: deck.Deck
	(*DeckContentIds)(nil),      // 1: deck.DeckContentIds
	(*DeckContents)(nil),        // 2: deck.DeckContents
	(*meta.MTGJSONAPIMeta)(nil), // 3: meta.MTGJSONAPIMeta
	(*card.CardSet)(nil),        // 4: card.CardSet
}
var file_deck_deck_proto_depIdxs = []int32{
	1, // 0: deck.Deck.contentIds:type_name -> deck.DeckContentIds
	2, // 1: deck.Deck.contents:type_name -> deck.DeckContents
	3, // 2: deck.Deck.mtgjsonApiMeta:type_name -> meta.MTGJSONAPIMeta
	4, // 3: deck.DeckContents.mainBoard:type_name -> card.CardSet
	4, // 4: deck.DeckContents.sideBoard:type_name -> card.CardSet
	4, // 5: deck.DeckContents.commander:type_name -> card.CardSet
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_deck_deck_proto_init() }
func file_deck_deck_proto_init() {
	if File_deck_deck_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deck_deck_proto_rawDesc), len(file_deck_deck_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deck_deck_proto_goTypes,
		DependencyIndexes: file_deck_deck_proto_depIdxs,
		MessageInfos:      file_deck_deck_proto_msgTypes,
	}.Build()
	File_deck_deck_proto = out.File
	file_deck_deck_proto_goTypes = nil
	file_deck_deck_proto_depIdxs = nil
}
