// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/login.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginRequest - Represents a login request to be sent to the /login endpoint
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" bson:"email"`       // @gotags: bson:"email"
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" bson:"password"` // @gotags: bson:"password"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_api_login_proto protoreflect.FileDescriptor

const file_api_login_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/login.proto\x12\x03api\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpasswordB*Z(github.com/stevezaluk/mtgjson-models/apib\x06proto3"

var (
	file_api_login_proto_rawDescOnce sync.Once
	file_api_login_proto_rawDescData []byte
)

func file_api_login_proto_rawDescGZIP() []byte {
	file_api_login_proto_rawDescOnce.Do(func() {
		file_api_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_login_proto_rawDesc), len(file_api_login_proto_rawDesc)))
	})
	return file_api_login_proto_rawDescData
}

var file_api_login_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_login_proto_goTypes = []any{
	(*LoginRequest)(nil), // 0: api.LoginRequest
}
var file_api_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_login_proto_init() }
func file_api_login_proto_init() {
	if File_api_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_login_proto_rawDesc), len(file_api_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_login_proto_goTypes,
		DependencyIndexes: file_api_login_proto_depIdxs,
		MessageInfos:      file_api_login_proto_msgTypes,
	}.Build()
	File_api_login_proto = out.File
	file_api_login_proto_goTypes = nil
	file_api_login_proto_depIdxs = nil
}
