// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/response.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// APIResponse - Represents a generic API response that can get returned from the API.
// Some fields are not used and will be nulled out on response
type APIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty" bson:"message"`             // @gotags: bson:"message"
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty" bson:"err"`                     // @gotags: bson:"err"
	RequiredScope string                 `protobuf:"bytes,3,opt,name=requiredScope,proto3" json:"requiredScope,omitempty" bson:"requiredScope"` // @gotags: bson:"requiredScope"
	NoExistCards  []string               `protobuf:"bytes,4,rep,name=noExistCards,proto3" json:"noExistCards,omitempty" bson:"noExistCards"`   // @gotags: bson:"noExistCards"
	InvalidCards  []string               `protobuf:"bytes,5,rep,name=invalidCards,proto3" json:"invalidCards,omitempty" bson:"invalidCards"`   // @gotags: bson:"invalidCards"
	DeckCode      string                 `protobuf:"bytes,6,opt,name=deckCode,proto3" json:"deckCode,omitempty" bson:"deckCode"`           // @gotags: bson:"deckCode"
	SetCode       string                 `protobuf:"bytes,7,opt,name=setCode,proto3" json:"setCode,omitempty" bson:"setCode"`             // @gotags: bson:"setCode"
	CardId        string                 `protobuf:"bytes,8,opt,name=cardId,proto3" json:"cardId,omitempty" bson:"cardId"`               // @gotags: bson:"cardId"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	mi := &file_api_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_api_response_proto_rawDescGZIP(), []int{0}
}

func (x *APIResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APIResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *APIResponse) GetRequiredScope() string {
	if x != nil {
		return x.RequiredScope
	}
	return ""
}

func (x *APIResponse) GetNoExistCards() []string {
	if x != nil {
		return x.NoExistCards
	}
	return nil
}

func (x *APIResponse) GetInvalidCards() []string {
	if x != nil {
		return x.InvalidCards
	}
	return nil
}

func (x *APIResponse) GetDeckCode() string {
	if x != nil {
		return x.DeckCode
	}
	return ""
}

func (x *APIResponse) GetSetCode() string {
	if x != nil {
		return x.SetCode
	}
	return ""
}

func (x *APIResponse) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

var File_api_response_proto protoreflect.FileDescriptor

const file_api_response_proto_rawDesc = "" +
	"\n" +
	"\x12api/response.proto\x12\x03api\"\xf5\x01\n" +
	"\vAPIResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\x12$\n" +
	"\rrequiredScope\x18\x03 \x01(\tR\rrequiredScope\x12\"\n" +
	"\fnoExistCards\x18\x04 \x03(\tR\fnoExistCards\x12\"\n" +
	"\finvalidCards\x18\x05 \x03(\tR\finvalidCards\x12\x1a\n" +
	"\bdeckCode\x18\x06 \x01(\tR\bdeckCode\x12\x18\n" +
	"\asetCode\x18\a \x01(\tR\asetCode\x12\x16\n" +
	"\x06cardId\x18\b \x01(\tR\x06cardIdB*Z(github.com/stevezaluk/mtgjson-models/apib\x06proto3"

var (
	file_api_response_proto_rawDescOnce sync.Once
	file_api_response_proto_rawDescData []byte
)

func file_api_response_proto_rawDescGZIP() []byte {
	file_api_response_proto_rawDescOnce.Do(func() {
		file_api_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_response_proto_rawDesc), len(file_api_response_proto_rawDesc)))
	})
	return file_api_response_proto_rawDescData
}

var file_api_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_response_proto_goTypes = []any{
	(*APIResponse)(nil), // 0: api.APIResponse
}
var file_api_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_response_proto_init() }
func file_api_response_proto_init() {
	if File_api_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_response_proto_rawDesc), len(file_api_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_response_proto_goTypes,
		DependencyIndexes: file_api_response_proto_depIdxs,
		MessageInfos:      file_api_response_proto_msgTypes,
	}.Build()
	File_api_response_proto = out.File
	file_api_response_proto_goTypes = nil
	file_api_response_proto_depIdxs = nil
}
